image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  VERSION: 1.2.1
    # BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
    # VCS_REF: ${CIRCLE_SHA1:0:7}
    # TAG: ${VERSION}-cpu-alpine
    # TAG_MINOR: ${VERSION%.*}-cpu-alpine
    # TAG_MAJOR: ${VERSION%%.*}-cpu-alpine"

services:
  - docker:dind

before_script:
  - docker info
  - export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - export VCS_REF=${CI_BUILD_REF:0:7}
  - export TAG=${VERSION}-cpu-alpine
  - export TAG_MINOR=${VERSION%.*}-cpu-alpine
  - export TAG_MAJOR=${VERSION%%.*}-cpu-alpine
  - export EXTRA_BAZEL_ARGS="--local_resources 3072,1.0,1.0"

stages:
  - build
  - test
  - deploy

image-build:
  stage: build
  script:
    - docker build 
      --build-arg BUILD_DATE=${BUILD_DATE} 
      --build-arg VCS_REF=${VCS_REF} 
      --build-arg VERSION=${VERSION} 
      --build-arg "EXTRA_BAZEL_ARGS=${EXTRA_BAZEL_ARGS}" 
      --rm -t smizy/keras-tensorflow:${TAG} .
    - docker images | grep keras-tensorflow

image-test:
  stage: test
  script:
    - docker inspect smizy/keras-tensorflow:${TAG}
    - docker run smizy/keras-tensorflow:${TAG} python -c 'import keras'

image-deploy:
  stage: deploy
  script:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag smizy/keras-tensorflow:${TAG} smizy/keras-tensorflow
    - docker tag smizy/keras-tensorflow:${TAG} smizy/keras-tensorflow:${TAG_MINOR}
#     - docker tag smizy/keras-tensorflow:${TAG} smizy/keras-tensorflow:${TAG_MAJOR}
    - docker push smizy/keras-tensorflow:${TAG}
    - docker push smizy/keras-tensorflow:${TAG_MINOR}
#     - docker push smizy/keras-tensorflow:${TAG_MAJOR}
    - docker push smizy/keras-tensorflow:latest
    - docker logout
    - curl -X POST 'https://hooks.microbadger.com/images/smizy/keras-tensorflow/kZzvRF3AJodLAJeVZ8aVSKyupOI='